from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.microsoft.azure.hooks.data_lake import AzureDataLakeStorageV2Hook
from datetime import datetime

ADLS_CONN_ID = "azure_con"
ADLS_CONTAINER = "raw-zone"

print(">>> adls_transform_dag.py loaded by Airflow parser")

def transform_adls_file(**context):
    # ✅ Keep heavy imports inside the function
    import os, tempfile, glob
    from pyspark.sql import SparkSession
    from pyspark.sql.functions import current_timestamp

    SOURCE_PATH = "non_fan_touchpoints/industry.csv"
    TARGET_PATH = "non_fan_touchpoints/processed/industry.csv"

    adls_hook = AzureDataLakeStorageV2Hook(adls_conn_id=ADLS_CONN_ID)
    adls_conn = adls_hook.get_conn()
    file_system_client = adls_conn.get_file_system_client(ADLS_CONTAINER)

    file_client = file_system_client.get_file_client(SOURCE_PATH)
    download = file_client.download_file()
    file_data = download.readall()

    with tempfile.NamedTemporaryFile(delete=False, suffix=".csv") as tmp_file:
        tmp_file.write(file_data)
        tmp_path = tmp_file.name

    spark = SparkSession.builder.appName("ADLS_Spark_SingleFile").getOrCreate()
    df = spark.read.option("header", "true").csv(tmp_path)
    df_transformed = df.withColumn("processed_at", current_timestamp())

    out_dir = tempfile.mkdtemp()
    df_transformed.coalesce(1).write.option("header", "true").mode("overwrite").csv(out_dir)

    part_files = glob.glob(os.path.join(out_dir, "part-*.csv"))
    if not part_files:
        raise FileNotFoundError("No output part file generated by Spark.")

    with open(part_files[0], "rb") as f:
        transformed_bytes = f.read()

    target_file_client = file_system_client.get_file_client(TARGET_PATH)
    target_file_client.upload_data(transformed_bytes, overwrite=True)


with DAG(
    dag_id="adls_transform_dag",
    start_date=datetime(2023, 1, 1),
    schedule=None,
    catchup=False,
) as dag:

    transform_csv_task = PythonOperator(
        task_id="transform_csv_task",
        python_callable=transform_adls_file,
    )